# Generated by Django 4.1.7 on 2023-03-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=5)),
                ('Name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('v_type', models.IntegerField()),
                ('v_number', models.CharField(max_length=50)),
                ('payment', models.IntegerField()),
                ('Created_onn', models.DateTimeField()),
            ],
        ),
    ]
