# Generated by Django 4.1.7 on 2023-03-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0002_exit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('sub', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=500)),
                ('Created_on', models.DateTimeField()),
            ],
        ),
    ]
