# Generated by Django 4.1.7 on 2023-03-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='mail',
            new_name='E_mail',
        ),
    ]
