# Generated by Django 4.1.7 on 2023-04-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0004_rename_mail_feedback_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='Created_on',
            field=models.DateTimeField(verbose_name='Date Of Creation'),
        ),
        migrations.AlterField(
            model_name='add',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='add',
            name='payment',
            field=models.IntegerField(choices=[(1, 'Paid'), (2, 'Not Paid')], verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='add',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Phone no'),
        ),
        migrations.AlterField(
            model_name='add',
            name='token',
            field=models.CharField(max_length=5, verbose_name='Token Number'),
        ),
        migrations.AlterField(
            model_name='add',
            name='v_number',
            field=models.CharField(max_length=50, verbose_name='Vehicle Number'),
        ),
        migrations.AlterField(
            model_name='add',
            name='v_type',
            field=models.IntegerField(choices=[(1, 'Two Wheeler'), (2, 'Four Wheeler')], verbose_name='Vehicle Type'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Created_on',
            field=models.DateTimeField(verbose_name='Date of Creation'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='E_mail',
            field=models.CharField(max_length=50, verbose_name='E Mail'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='msg',
            field=models.CharField(max_length=500, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sub',
            field=models.CharField(max_length=50, verbose_name='Subject'),
        ),
    ]
