# Generated by Django 4.1.7 on 2023-04-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0006_add_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
