# Generated by Django 4.1.7 on 2023-04-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0007_exit_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exit',
            name='uid',
        ),
    ]
