# Generated by Django 4.1.7 on 2023-04-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0008_remove_exit_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='v_park',
            field=models.CharField(default=1, max_length=50, verbose_name='Vehicle Prak By'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exit',
            name='v_park',
            field=models.CharField(default=1, max_length=50, verbose_name='Vehicle Prak By'),
            preserve_default=False,
        ),
    ]
